---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heimdall-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: heimdall
        category: edge
    spec:
      containers:
      - name: heimdall
        image: your_image_here
        env:
        - name: com.google.iap.audience
          value: "YOUR_AUDIENCE_HERE"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: "/heimdall-health"
            port: 8080
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: "/heimdall-health"
            port: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: 1
          requests:
            memory: 256Mi
            cpu: 0.5
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - heimdall
              topologyKey: kubernetes.io/hostname
