apiVersion: v1
kind: Service
metadata:
  name: heimdall
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  AuthService
      name:  authentication
      auth_service: "heimdall.default.svc.cluster.local.:8080"
      allowed_headers:
      - "x-iap-user-email"
spec:
  ports:
  - protocol: TCP
    port: 8080
  selector:
    app: heimdall
